# Generated by Django 2.2.13 on 2021-05-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210522_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='author',
        ),
    ]
