# Generated by Django 2.2.13 on 2021-05-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210522_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='user',
        ),
    ]
